CREATE TABLE posts (
  id INTEGER PRIMARY KEY NOT NULL,
  id_user TEXT NOT NULL REFERENCES users(id),
  content TEXT NOT NULL,
  id_parent INTEGER NULL REFERENCES posts(id),
  at TEXT NOT NULL
);

CREATE TABLE users (
  id INTEGER PRIMARY KEY NOT NULL,
  email TEXT NOT NULL UNIQUE
);

CREATE TABLE tokens (
  id INTEGER PRIMARY KEY NOT NULL,
  token TEXT UNIQUE NOT NULL,
  id_user INTEGER NOT NULL,
  FOREIGN KEY(id_user) REFERENCES users(id)
);

CREATE TABLE codes (
  code TEXT PRIMARY KEY NOT NULL,
  generated_at TEXT NOT NULL,
  valid INTEGER NOT NULL,
  id_user INTEGER NOT NULL,
  FOREIGN KEY(id_user) REFERENCES users(id)
);
